#!/usr/bin/env python3
"""Write src/framecycler/_version.py with git build metadata."""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parents[1] / "src" / "framecycler" / "_version.py"
APP_VERSION = "0.0.1"


def git(*args: str) -> str:
    return subprocess.check_output(
        ["git", *args], cwd=ROOT, stderr=subprocess.DEVNULL
    ).decode().strip()


def is_dirty() -> bool:
    if subprocess.call(["git", "diff", "--quiet"], cwd=ROOT) != 0:
        return True
    if subprocess.call(["git", "diff", "--cached", "--quiet"], cwd=ROOT) != 0:
        return True
    return False


def main() -> int:
    try:
        commit = git("rev-parse", "HEAD")
        commit_short = git("rev-parse", "--short", "HEAD")
        branch = git("branch", "--show-current") or "detached"
        dirty = is_dirty()
    except (subprocess.CalledProcessError, FileNotFoundError):
        commit = "unknown"
        commit_short = "unknown"
        branch = "unknown"
        dirty = False

    OUT.write_text(
        "# Auto-generated by scripts/generate_version.py — do not edit.\n"
        f'__version__ = "{APP_VERSION}"\n'
        f'__commit__ = "{commit}"\n'
        f'__commit_short__ = "{commit_short}"\n'
        f'__branch__ = "{branch}"\n'
        f"__dirty__ = {dirty}\n",
        encoding="utf-8",
    )
    print(f"Wrote build metadata to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
