#!/usr/bin/env python3
"""Write src/framecycler/_version.py with git build metadata."""

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parents[1] / "src" / "framecycler" / "_version.py"
DEFAULT_VERSION = "0.2.1"


def git(*args: str) -> str:
    return subprocess.check_output(
        ["git", *args], cwd=ROOT, stderr=subprocess.DEVNULL
    ).decode().strip()


def is_dirty() -> bool:
    if subprocess.call(["git", "diff", "--quiet"], cwd=ROOT) != 0:
        return True
    if subprocess.call(["git", "diff", "--cached", "--quiet"], cwd=ROOT) != 0:
        return True
    return False


def normalize_version(raw: str) -> str:
    return raw.strip().lstrip("v")


def resolve_version(cli_version: str | None = None) -> str:
    if cli_version:
        return normalize_version(cli_version)

    env_version = os.environ.get("APP_VERSION", "").strip()
    if env_version:
        return normalize_version(env_version)

    try:
        tag = git("describe", "--tags", "--abbrev=0")
        return normalize_version(tag)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return DEFAULT_VERSION


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Framecycler build metadata.")
    parser.add_argument(
        "--version",
        help="Application semver (overrides APP_VERSION env and git tag detection).",
    )
    args = parser.parse_args()
    app_version = resolve_version(args.version)

    try:
        commit = git("rev-parse", "HEAD")
        commit_short = git("rev-parse", "--short", "HEAD")
        branch = git("branch", "--show-current") or "detached"
        dirty = is_dirty()
    except (subprocess.CalledProcessError, FileNotFoundError):
        commit = "unknown"
        commit_short = "unknown"
        branch = "unknown"
        dirty = False

    OUT.write_text(
        "# Auto-generated by scripts/generate_version.py — do not edit.\n"
        f'__version__ = "{app_version}"\n'
        f'__commit__ = "{commit}"\n'
        f'__commit_short__ = "{commit_short}"\n'
        f'__branch__ = "{branch}"\n'
        f"__dirty__ = {dirty}\n",
        encoding="utf-8",
    )
    print(f"Wrote build metadata to {OUT} (version={app_version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
